apis:
  facebook:
    api_key: "541756572610649"
    api_secret: "eca953142e00aa1b538e59739805e131"
    access_requirements: "id, name, first_name, last_name, email, gender, age_range, user_birthday, read_friendlists"